recursive: true
force-file-write: true
dir: "mocks/{{ .SrcPackagePath }}"
filename: "mock_{{ .InterfaceName }}.go"
pkgname: "{{ .SrcPackageName }}Mocks"
structname: "Mock{{ .InterfaceName }}"
template: testify
formatter: "goimports"
packages:
  github.com/thewizardplusplus/go-tcp-server:
    interfaces:
      ConnectionHandler:
      ServerProtocol:
        config:
          dir: "mocks/external/{{ .SrcPackagePath }}"
          pkgname: "{{ .SrcPackageName }}ExternalMocks"
      ClientProtocol:
        config:
          dir: "mocks/external/{{ .SrcPackagePath }}"
          pkgname: "{{ .SrcPackageName }}ExternalMocks"
      RequestHandler:
        config:
          dir: "mocks/external/{{ .SrcPackagePath }}"
          pkgname: "{{ .SrcPackageName }}ExternalMocks"
      netConn:
      errorHandler:
