// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tcpServerMocks

import (
	"net"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMocknetConn creates a new instance of MocknetConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocknetConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocknetConn {
	mock := &MocknetConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MocknetConn is an autogenerated mock type for the netConn type
type MocknetConn struct {
	mock.Mock
}

type MocknetConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MocknetConn) EXPECT() *MocknetConn_Expecter {
	return &MocknetConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MocknetConn
func (_mock *MocknetConn) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MocknetConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MocknetConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MocknetConn_Expecter) Close() *MocknetConn_Close_Call {
	return &MocknetConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MocknetConn_Close_Call) Run(run func()) *MocknetConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MocknetConn_Close_Call) Return(err error) *MocknetConn_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MocknetConn_Close_Call) RunAndReturn(run func() error) *MocknetConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// LocalAddr provides a mock function for the type MocknetConn
func (_mock *MocknetConn) LocalAddr() net.Addr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LocalAddr")
	}

	var r0 net.Addr
	if returnFunc, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}
	return r0
}

// MocknetConn_LocalAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalAddr'
type MocknetConn_LocalAddr_Call struct {
	*mock.Call
}

// LocalAddr is a helper method to define mock.On call
func (_e *MocknetConn_Expecter) LocalAddr() *MocknetConn_LocalAddr_Call {
	return &MocknetConn_LocalAddr_Call{Call: _e.mock.On("LocalAddr")}
}

func (_c *MocknetConn_LocalAddr_Call) Run(run func()) *MocknetConn_LocalAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MocknetConn_LocalAddr_Call) Return(addr net.Addr) *MocknetConn_LocalAddr_Call {
	_c.Call.Return(addr)
	return _c
}

func (_c *MocknetConn_LocalAddr_Call) RunAndReturn(run func() net.Addr) *MocknetConn_LocalAddr_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MocknetConn
func (_mock *MocknetConn) Read(b []byte) (int, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MocknetConn_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MocknetConn_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - b
func (_e *MocknetConn_Expecter) Read(b interface{}) *MocknetConn_Read_Call {
	return &MocknetConn_Read_Call{Call: _e.mock.On("Read", b)}
}

func (_c *MocknetConn_Read_Call) Run(run func(b []byte)) *MocknetConn_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MocknetConn_Read_Call) Return(n int, err error) *MocknetConn_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MocknetConn_Read_Call) RunAndReturn(run func(b []byte) (int, error)) *MocknetConn_Read_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteAddr provides a mock function for the type MocknetConn
func (_mock *MocknetConn) RemoteAddr() net.Addr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteAddr")
	}

	var r0 net.Addr
	if returnFunc, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}
	return r0
}

// MocknetConn_RemoteAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteAddr'
type MocknetConn_RemoteAddr_Call struct {
	*mock.Call
}

// RemoteAddr is a helper method to define mock.On call
func (_e *MocknetConn_Expecter) RemoteAddr() *MocknetConn_RemoteAddr_Call {
	return &MocknetConn_RemoteAddr_Call{Call: _e.mock.On("RemoteAddr")}
}

func (_c *MocknetConn_RemoteAddr_Call) Run(run func()) *MocknetConn_RemoteAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MocknetConn_RemoteAddr_Call) Return(addr net.Addr) *MocknetConn_RemoteAddr_Call {
	_c.Call.Return(addr)
	return _c
}

func (_c *MocknetConn_RemoteAddr_Call) RunAndReturn(run func() net.Addr) *MocknetConn_RemoteAddr_Call {
	_c.Call.Return(run)
	return _c
}

// SetDeadline provides a mock function for the type MocknetConn
func (_mock *MocknetConn) SetDeadline(t time.Time) error {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetDeadline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MocknetConn_SetDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeadline'
type MocknetConn_SetDeadline_Call struct {
	*mock.Call
}

// SetDeadline is a helper method to define mock.On call
//   - t
func (_e *MocknetConn_Expecter) SetDeadline(t interface{}) *MocknetConn_SetDeadline_Call {
	return &MocknetConn_SetDeadline_Call{Call: _e.mock.On("SetDeadline", t)}
}

func (_c *MocknetConn_SetDeadline_Call) Run(run func(t time.Time)) *MocknetConn_SetDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MocknetConn_SetDeadline_Call) Return(err error) *MocknetConn_SetDeadline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MocknetConn_SetDeadline_Call) RunAndReturn(run func(t time.Time) error) *MocknetConn_SetDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// SetReadDeadline provides a mock function for the type MocknetConn
func (_mock *MocknetConn) SetReadDeadline(t time.Time) error {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetReadDeadline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MocknetConn_SetReadDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadDeadline'
type MocknetConn_SetReadDeadline_Call struct {
	*mock.Call
}

// SetReadDeadline is a helper method to define mock.On call
//   - t
func (_e *MocknetConn_Expecter) SetReadDeadline(t interface{}) *MocknetConn_SetReadDeadline_Call {
	return &MocknetConn_SetReadDeadline_Call{Call: _e.mock.On("SetReadDeadline", t)}
}

func (_c *MocknetConn_SetReadDeadline_Call) Run(run func(t time.Time)) *MocknetConn_SetReadDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MocknetConn_SetReadDeadline_Call) Return(err error) *MocknetConn_SetReadDeadline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MocknetConn_SetReadDeadline_Call) RunAndReturn(run func(t time.Time) error) *MocknetConn_SetReadDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// SetWriteDeadline provides a mock function for the type MocknetConn
func (_mock *MocknetConn) SetWriteDeadline(t time.Time) error {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetWriteDeadline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MocknetConn_SetWriteDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWriteDeadline'
type MocknetConn_SetWriteDeadline_Call struct {
	*mock.Call
}

// SetWriteDeadline is a helper method to define mock.On call
//   - t
func (_e *MocknetConn_Expecter) SetWriteDeadline(t interface{}) *MocknetConn_SetWriteDeadline_Call {
	return &MocknetConn_SetWriteDeadline_Call{Call: _e.mock.On("SetWriteDeadline", t)}
}

func (_c *MocknetConn_SetWriteDeadline_Call) Run(run func(t time.Time)) *MocknetConn_SetWriteDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Time))
	})
	return _c
}

func (_c *MocknetConn_SetWriteDeadline_Call) Return(err error) *MocknetConn_SetWriteDeadline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MocknetConn_SetWriteDeadline_Call) RunAndReturn(run func(t time.Time) error) *MocknetConn_SetWriteDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MocknetConn
func (_mock *MocknetConn) Write(b []byte) (int, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MocknetConn_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MocknetConn_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - b
func (_e *MocknetConn_Expecter) Write(b interface{}) *MocknetConn_Write_Call {
	return &MocknetConn_Write_Call{Call: _e.mock.On("Write", b)}
}

func (_c *MocknetConn_Write_Call) Run(run func(b []byte)) *MocknetConn_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MocknetConn_Write_Call) Return(n int, err error) *MocknetConn_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MocknetConn_Write_Call) RunAndReturn(run func(b []byte) (int, error)) *MocknetConn_Write_Call {
	_c.Call.Return(run)
	return _c
}
