name: lint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
